### ISSUE TITLE
Only use PartUUID on a GPT rootfs

### ISSUE THREAD

**Issue by ikeydoherty** [ikeydoherty/clr-boot-manager#53]
Scenario:

 - UEFI system
 - GPT disk contains `ESP`
 - `MBR` disk contains `/`

Problem:

 - cbm detects `PartUUID` & `UUID`  for GPT converted to MBR
 - cbm writes `root=PARTUUID=` with an unsupported `PartUUID`

Currently, if we find an ESP, we niavely assume GPT. The `probe` code must be modified to determine if the root device is `GPT` or not.  If it is GPT, we should write the PartUUID, otherwise free and NULL the PartUUID and write only the UUID.

**Comment by lebjortvedt** [comment]
Is there a workaround for this? My laptop won't boot now and I see that the entry is like this _root=PARTUUID=_ 😢

**Comment by ikeydoherty** [comment]
@lebjortvedt do you have an MBR rootfs disk?

**Comment by lebjortvedt** [comment]
@ikeydoherty I'm sorry but I'm not sure what you mean. 
I attach a screenshot from Easeus Partition Manager. I run Windows 10 as well on the laptop, and I have one SSD and one spinning disk installed. I have marked the partitions used in Solus with red lines:

![image](https://cloud.githubusercontent.com/assets/13777970/24423406/20a49966-13fd-11e7-8fe8-5aabb943cedf.png)

**Comment by ikeydoherty** [comment]
Right so your OS is installed on the GPT disk?

**Comment by lebjortvedt** [comment]
Correct. The MBR disk is just storage. 
It also seems to me that the UUID in the boot loader is the same as the partition editor sees:

![disk](https://cloud.githubusercontent.com/assets/13777970/24424103/aec3d41c-13ff-11e7-806a-93051815460b.png)

![bilde 28 03 2017 18 31 54](https://cloud.githubusercontent.com/assets/13777970/24424116/be09c9e0-13ff-11e7-816d-f92888bcb1d0.jpg)

**Comment by ikeydoherty** [comment]
OK what happens when you try to boot?

**Comment by lebjortvedt** [comment]
I get this error:
![fil 28 03 2017 18 00 20](https://cloud.githubusercontent.com/assets/13777970/24424671/aebe7718-1401-11e7-811c-26ef5e1a5480.jpeg)

But the file looks like it's there:
![efi](https://cloud.githubusercontent.com/assets/13777970/24424699/dd87ea20-1401-11e7-9167-c4df7de0b1c4.png)

**Comment by ikeydoherty** [comment]
Is there any way I can see the `\loader\entries\Solus*` file ?

**Comment by lebjortvedt** [comment]
title Solus 2017.01.01.0
linux /EFI/com.solus-project/kernel-com.solus-project.lts.4.9.18-10
initrd /EFI/com.solus-project/initrd-com.solus-project.lts.4.9.18-10
options root=PARTUUID=59a2798c-326a-4249-8b02-488d825ba97d quiet ro splash

**Comment by ikeydoherty** [comment]
OK so the files on the `linux` and `initrd` lines, they *definitely* exist?

**Comment by lebjortvedt** [comment]
According to the previous picture - yes.
I mounted the EFI partition in Windows using the command line, and I can navigate around. However, if I open the EFI/com.solus-project folder and type "dir" _Windows_ gives me an error:

![error](https://cloud.githubusercontent.com/assets/13777970/24425373/4b215d08-1404-11e7-9a39-a918a80abfeb.png)

**Comment by ikeydoherty** [comment]
What if you do run chkdsk - is it restorable?

**Comment by lebjortvedt** [comment]
Hahaha, now it all went to h*ll 😄 
Chkdsk said that it corrected it, but the _com.solus-project_ is now gone.

Don't know if it is possible to manually create the folder and insert the proper files there?

**Comment by ikeydoherty** [comment]
The only way to do this is with  a chroot repair from a livecd - and i think clr-boot-manager is going to throw up because of #54 :/

**Comment by lebjortvedt** [comment]
Maybe a stupid question, but will it work to reinstall the OS? The home partition can be spared, so that's not a big deal :)

**Comment by ikeydoherty** [comment]
Well - if you're up for reinstalling, I can make an unstable Solus ISO with clr-boot-manager integration if you're willing to test? We need to see how it works out for clr-boot-manager too :)

**Comment by lebjortvedt** [comment]
Sure, that'd be great :) 
I suppose I'll wipe the root file system and keep the home partition then.
Too tired to try tonight though 😄

**Comment by ikeydoherty** [comment]
That's alright - it'll take me a short while to do the ISO :)

**Comment by lebjortvedt** [comment]
Thanks! And thanks for the help so far :)

**Comment by ikeydoherty** [comment]
OK I'll be pushing a fix for this shortly - just writing the test suite

**Comment by lebjortvedt** [comment]
Awesome :) Will I able to install from USB?

Sendt fra mobiltelefon
Med vennlig hilsen/Best regards
Lars-Eivind Bjørtvedt

**Comment by ikeydoherty** [comment]
Yep, once I have it all written up, I'll test it local, then put up a PR. Once I've finished work I'll create a new Solus ISO with the new cbm

**Comment by ikeydoherty** [comment]
This behaviour has landed in 1.5.1 - I'll now get this into Solus and a test ISO together

**Comment by ikeydoherty** [comment]
Alright spinning the ISO now, will let you know when its uploaded

**Comment by jamesmshaker** [comment]
Excellent!!! I'll burn a USB and try it.

James

**Comment by lebjortvedt** [comment]
Same here :)

**Comment by ikeydoherty** [comment]
Uploading....

**intensity intensifies**

**Comment by ikeydoherty** [comment]
ISO File: https://archive.solus-project.com/.donotdistribute/Solus-Q1-CBM-Validation.iso

```
5301562f26406215762420bf305f1d5c986de0a2dd2fc62b3a114257b7be9e8e  Solus-Q1-CBM-Validation.iso
```

**Comment by lebjortvedt** [comment]
Here goes!

Sendt fra mobiltelefon
Med vennlig hilsen/Best regards
Lars-Eivind Bjørtvedt

**Comment by jamesmshaker** [comment]
Still no successful boot for me.

James

**Comment by ikeydoherty** [comment]
Details..?

**Comment by jamesmshaker** [comment]
It still could be my error somewhere along the way.   I use Gparted to
create a swap, /, and efi (512MB fat32) partition on a Nvme ssd.  I put the
dell precision m7510 into uefi mode but enable it to recognize legacy ROMS
(so the live USB will boot).  I boot the live Solus and install.
Everything seems to go ok but when it comes time to reboot and I reboot,
Solus isn't found.

James

**Comment by ikeydoherty** [comment]
> but enable it to recognize legacy ROMS (so the live USB will boot)

Uh what? The image is UEFI/Legacy hybrid. It does *not* need legacy support. Sounds like you either booted or wrote it wrong.

**Comment by jamesmshaker** [comment]
When I use rufus to try and write the solus iso to the usb stick and select
the GPT uefi optionI get this error:

When using UEFI Target Type, only EFI bootable ISO images are supported.
Please select an EFI bootable ISO or set the Tartget type to BIOS.

**Comment by ikeydoherty** [comment]
..? You need to write the image *as is*, unmodified. Don't let rufus butcher it.

**Comment by JoshStrobl** [comment]
Choose the DD Image Mode as per [our documentation](https://solus-project.com/articles/installation/preparing-to-install/en/#usb-3).

**Comment by lebjortvedt** [comment]
It worked for me :+1: 
I reinstalled the root file system but kept the home partition, and that worked. 
The first time I tried to log in everything locked up - but the next times it's worked flawlessly.
The only difference now is that the (dual)boot menu is skipped unless I press the e-key.

**Comment by ikeydoherty** [comment]
```
sudo clr-boot-manager set-timeout some-timeout-value
sudo clr-boot-manager update
```

**Comment by lebjortvedt** [comment]
Worked like a charm!
Thanks a lot for everything 😀

**Comment by ikeydoherty** [comment]
Awesome thanks! I'll close this issue now then
