### ISSUE TITLE
Multiple Kernel Versions at Goofiboot

### ISSUE THREAD

**Issue by tayspen72** [ikeydoherty/clr-boot-manager#65]
With the update of the clr-boot-manager, the goofiboot is now showing multiple kernel versions as possible boot options. I have ran the clr-boot-manager report-booted and update but the current and previous options remain. I would like to remove the previous option and old kernel data stored but cannot find information on how to do so under the manpages for clr-boot-manager. Suggestions?

**Comment by ikeydoherty** [comment]
Are they all CBM managed kernels? It could be an artefact of the transition:

```
ls -lRa /boot
ls -lRa /usr/lib/kernel
```

**Comment by tayspen72** [comment]
Here is the output. I am dual booted with windows, as this obviously shows.

$ ls -lRa /boot
/boot:
total 38408
drwxr-xr-x  3 root root     4096 Apr  3 11:14 .
drwxr-xr-x 17 root root     4096 Apr  3 11:10 ..
lrwxrwxrwx  1 root root        1 Apr  3 05:03 boot -> .
drwxr-xr-x  6 root root     4096 Dec 31  1969 efi
-rw-------  1 root root 19650869 Jan  1 13:17 initramfs-4.8.15.img
-rw-------  1 root root 19664245 Apr  3 11:14 initramfs-4.9.20-12.lts.img

/boot/efi:
total 24
drwxr-xr-x 6 root root 4096 Dec 31  1969  .
drwxr-xr-x 3 root root 4096 Apr  3 11:14  ..
drwxr-xr-x 6 root root 4096 Mar 27 10:35  EFI
drwxr-xr-x 3 root root 4096 Apr  4 07:59  loader
drwxr-xr-x 2 root root 4096 Oct 23 13:26 'System Volume Information'
drwxr-xr-x 4 root root 4096 Oct 14 01:22  .Trash-1000

/boot/efi/EFI:
total 24
drwxr-xr-x 6 root root 4096 Mar 27 10:35 .
drwxr-xr-x 6 root root 4096 Dec 31  1969 ..
drwxr-xr-x 2 root root 4096 Apr  3 11:07 Boot
drwxr-xr-x 2 root root 4096 Apr  2 09:27 com.solus-project
drwxr-xr-x 2 root root 4096 Apr  3 11:07 goofiboot
drwxr-xr-x 4 root root 4096 Mar 29  2016 Microsoft

/boot/efi/EFI/Boot:
total 92
drwxr-xr-x 2 root root  4096 Apr  3 11:07 .
drwxr-xr-x 6 root root  4096 Mar 27 10:35 ..
-rwxr-xr-x 1 root root 85227 Oct 18 00:00 BOOTX64.EFI

/boot/efi/EFI/com.solus-project:
total 52872
drwxr-xr-x 2 root root     4096 Apr  2 09:27 .
drwxr-xr-x 6 root root     4096 Mar 27 10:35 ..
-rwxr-xr-x 1 root root 19973450 Mar 27 10:35 initrd-com.solus-project.lts.4.9.18-10
-rwxr-xr-x 1 root root 20343328 Apr  2 09:27 initrd-com.solus-project.lts.4.9.20-12
-rwxr-xr-x 1 root root  6903376 Mar 27 10:35 kernel-com.solus-project.lts.4.9.18-10
-rwxr-xr-x 1 root root  6903376 Apr  2 09:27 kernel-com.solus-project.lts.4.9.20-12

/boot/efi/EFI/goofiboot:
total 92
drwxr-xr-x 2 root root  4096 Apr  3 11:07 .
drwxr-xr-x 6 root root  4096 Mar 27 10:35 ..
-rwxr-xr-x 1 root root 85227 Oct 18 00:00 goofibootx64.efi

/boot/efi/EFI/Microsoft:
total 20
drwxr-xr-x  4 root root 4096 Mar 29  2016 .
drwxr-xr-x  6 root root 4096 Mar 27 10:35 ..
drwxr-xr-x 42 root root 8192 Mar 29  2016 Boot
drwxr-xr-x  2 root root 4096 Mar 29  2016 Recovery

/boot/efi/EFI/Microsoft/Boot:
total 4708
drwxr-xr-x 42 root root    8192 Mar 29  2016 .
drwxr-xr-x  4 root root    4096 Mar 29  2016 ..
-rwxr-xr-x  1 root root   45056 Apr  3 18:51 BCD
-rwxr-xr-x  1 root root   65536 Mar 29  2016 BCD.LOG
-rwxr-xr-x  1 root root       0 Mar 29  2016 BCD.LOG1
-rwxr-xr-x  1 root root       0 Mar 29  2016 BCD.LOG2
drwxr-xr-x  2 root root    4096 Oct 23 13:26 bg-BG
-rwxr-xr-x  1 root root 1193824 Mar  4 00:20 bootmgfw.efi
-rwxr-xr-x  1 root root 1178976 Mar  4 00:20 bootmgr.efi
-rwxr-xr-x  1 root root   65536 Oct 23 13:26 BOOTSTAT.DAT
-rwxr-xr-x  1 root root    4669 Jul 16  2016 boot.stl
drwxr-xr-x  2 root root    4096 Mar 29  2016 cs-CZ
drwxr-xr-x  2 root root    4096 Mar 29  2016 da-DK
drwxr-xr-x  2 root root    4096 Mar 29  2016 de-DE
drwxr-xr-x  2 root root    4096 Mar 29  2016 el-GR
drwxr-xr-x  2 root root    4096 Oct 23 13:26 en-GB
drwxr-xr-x  2 root root    4096 Mar 29  2016 en-US
drwxr-xr-x  2 root root    4096 Mar 29  2016 es-ES
drwxr-xr-x  2 root root    4096 Oct 23 13:26 es-MX
drwxr-xr-x  2 root root    4096 Oct 23 13:26 et-EE
drwxr-xr-x  2 root root    4096 Mar 29  2016 fi-FI
drwxr-xr-x  2 root root    4096 Mar 29  2016 Fonts
drwxr-xr-x  2 root root    4096 Oct 23 13:26 fr-CA
drwxr-xr-x  2 root root    4096 Mar 29  2016 fr-FR
drwxr-xr-x  2 root root    4096 Oct 23 13:26 hr-HR
drwxr-xr-x  2 root root    4096 Mar 29  2016 hu-HU
drwxr-xr-x  2 root root    4096 Mar 29  2016 it-IT
drwxr-xr-x  2 root root    4096 Mar 29  2016 ja-JP
-rwxr-xr-x  1 root root   29536 Jul 16  2016 kd_02_10df.dll
-rwxr-xr-x  1 root root  325984 Jul 16  2016 kd_02_10ec.dll
-rwxr-xr-x  1 root root   25440 Jul 16  2016 kd_02_1137.dll
-rwxr-xr-x  1 root root  212312 Jul 16  2016 kd_02_14e4.dll
-rwxr-xr-x  1 root root   42848 Jul 16  2016 kd_02_15b3.dll
-rwxr-xr-x  1 root root   39264 Jul 16  2016 kd_02_1969.dll
-rwxr-xr-x  1 root root   29536 Jul 16  2016 kd_02_19a2.dll
-rwxr-xr-x  1 root root  228192 Jul 16  2016 kd_02_8086.dll
-rwxr-xr-x  1 root root   17760 Jul 16  2016 kd_07_1415.dll
-rwxr-xr-x  1 root root   37728 Jul 16  2016 kd_0C_8086.dll
-rwxr-xr-x  1 root root   22368 Jul 16  2016 kdstub.dll
drwxr-xr-x  2 root root    4096 Mar 29  2016 ko-KR
drwxr-xr-x  2 root root    4096 Oct 23 13:26 lt-LT
drwxr-xr-x  2 root root    4096 Oct 23 13:26 lv-LV
-rwxr-xr-x  1 root root 1044832 Mar  4 00:19 memtest.efi
drwxr-xr-x  2 root root    4096 Mar 29  2016 nb-NO
drwxr-xr-x  2 root root    4096 Mar 29  2016 nl-NL
drwxr-xr-x  2 root root    4096 Mar 29  2016 pl-PL
drwxr-xr-x  2 root root    4096 Mar 29  2016 pt-BR
drwxr-xr-x  2 root root    4096 Mar 29  2016 pt-PT
drwxr-xr-x  2 root root    4096 Mar 29  2016 qps-ploc
drwxr-xr-x  3 root root    4096 Mar 29  2016 Resources
drwxr-xr-x  2 root root    4096 Oct 23 13:26 ro-RO
drwxr-xr-x  2 root root    4096 Mar 29  2016 ru-RU
drwxr-xr-x  2 root root    4096 Oct 23 13:26 sk-SK
drwxr-xr-x  2 root root    4096 Oct 23 13:26 sl-SI
drwxr-xr-x  2 root root    4096 Mar 29  2016 sr-Latn-CS
drwxr-xr-x  2 root root    4096 Oct 23 13:26 sr-Latn-RS
drwxr-xr-x  2 root root    4096 Mar 29  2016 sv-SE
drwxr-xr-x  2 root root    4096 Mar 29  2016 tr-TR
drwxr-xr-x  2 root root    4096 Oct 23 13:26 uk-UA
drwxr-xr-x  2 root root    4096 Mar 29  2016 zh-CN
drwxr-xr-x  2 root root    4096 Mar 29  2016 zh-HK
drwxr-xr-x  2 root root    4096 Mar 29  2016 zh-TW

/boot/efi/EFI/Microsoft/Boot/bg-BG:
total 164
drwxr-xr-x  2 root root  4096 Oct 23 13:26 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 77664 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 77664 Oct 23 15:52 bootmgr.efi.mui

/boot/efi/EFI/Microsoft/Boot/cs-CZ:
total 212
drwxr-xr-x  2 root root  4096 Mar 29  2016 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 76640 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 76640 Oct 23 15:52 bootmgr.efi.mui
-rwxr-xr-x  1 root root 45408 Oct 23 15:52 memtest.efi.mui

/boot/efi/EFI/Microsoft/Boot/da-DK:
total 212
drwxr-xr-x  2 root root  4096 Mar 29  2016 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 75616 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 75616 Oct 23 15:52 bootmgr.efi.mui
-rwxr-xr-x  1 root root 45408 Oct 23 15:52 memtest.efi.mui

/boot/efi/EFI/Microsoft/Boot/de-DE:
total 220
drwxr-xr-x  2 root root  4096 Mar 29  2016 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 79200 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 79200 Oct 23 15:52 bootmgr.efi.mui
-rwxr-xr-x  1 root root 45920 Oct 23 15:52 memtest.efi.mui

/boot/efi/EFI/Microsoft/Boot/el-GR:
total 220
drwxr-xr-x  2 root root  4096 Mar 29  2016 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 80224 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 80224 Oct 23 15:52 bootmgr.efi.mui
-rwxr-xr-x  1 root root 46424 Oct 23 15:52 memtest.efi.mui

/boot/efi/EFI/Microsoft/Boot/en-GB:
total 164
drwxr-xr-x  2 root root  4096 Oct 23 13:26 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 74080 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 74080 Oct 23 15:52 bootmgr.efi.mui

/boot/efi/EFI/Microsoft/Boot/en-US:
total 208
drwxr-xr-x  2 root root  4096 Mar 29  2016 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 74080 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 74080 Oct 23 15:52 bootmgr.efi.mui
-rwxr-xr-x  1 root root 44896 Oct 23 15:52 memtest.efi.mui

/boot/efi/EFI/Microsoft/Boot/es-ES:
total 212
drwxr-xr-x  2 root root  4096 Mar 29  2016 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 77664 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 77664 Oct 23 15:52 bootmgr.efi.mui
-rwxr-xr-x  1 root root 45912 Oct 23 15:52 memtest.efi.mui

/boot/efi/EFI/Microsoft/Boot/es-MX:
total 164
drwxr-xr-x  2 root root  4096 Oct 23 13:26 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 77664 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 77664 Oct 23 15:52 bootmgr.efi.mui

/boot/efi/EFI/Microsoft/Boot/et-EE:
total 164
drwxr-xr-x  2 root root  4096 Oct 23 13:26 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 75104 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 75104 Oct 23 15:52 bootmgr.efi.mui

/boot/efi/EFI/Microsoft/Boot/fi-FI:
total 212
drwxr-xr-x  2 root root  4096 Mar 29  2016 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 76640 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 76640 Oct 23 15:52 bootmgr.efi.mui
-rwxr-xr-x  1 root root 45408 Oct 23 15:52 memtest.efi.mui

/boot/efi/EFI/Microsoft/Boot/Fonts:
total 13184
drwxr-xr-x  2 root root    4096 Mar 29  2016 .
drwxr-xr-x 42 root root    8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 3695655 Sep  6  2016 chs_boot.ttf
-rwxr-xr-x  1 root root 3878349 Sep  6  2016 cht_boot.ttf
-rwxr-xr-x  1 root root 1985803 Sep  6  2016 jpn_boot.ttf
-rwxr-xr-x  1 root root 2372934 Sep  6  2016 kor_boot.ttf
-rwxr-xr-x  1 root root  176817 Sep  6  2016 malgun_boot.ttf
-rwxr-xr-x  1 root root  174366 Sep  6  2016 malgunn_boot.ttf
-rwxr-xr-x  1 root root  143110 Sep  6  2016 meiryo_boot.ttf
-rwxr-xr-x  1 root root  141493 Sep  6  2016 meiryon_boot.ttf
-rwxr-xr-x  1 root root  163498 Sep  6  2016 msjh_boot.ttf
-rwxr-xr-x  1 root root  161494 Sep  6  2016 msjhn_boot.ttf
-rwxr-xr-x  1 root root  154831 Sep  6  2016 msyh_boot.ttf
-rwxr-xr-x  1 root root  150729 Sep  6  2016 msyhn_boot.ttf
-rwxr-xr-x  1 root root   44798 Jul 16  2016 segmono_boot.ttf
-rwxr-xr-x  1 root root   85802 Jul 16  2016 segoen_slboot.ttf
-rwxr-xr-x  1 root root   86118 Jul 16  2016 segoe_slboot.ttf
-rwxr-xr-x  1 root root   49030 Jul 16  2016 wgl4_boot.ttf

/boot/efi/EFI/Microsoft/Boot/fr-CA:
total 172
drwxr-xr-x  2 root root  4096 Oct 23 13:26 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 79200 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 79200 Oct 23 15:52 bootmgr.efi.mui

/boot/efi/EFI/Microsoft/Boot/fr-FR:
total 220
drwxr-xr-x  2 root root  4096 Mar 29  2016 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 79200 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 79200 Oct 23 15:52 bootmgr.efi.mui
-rwxr-xr-x  1 root root 45920 Oct 23 15:52 memtest.efi.mui

/boot/efi/EFI/Microsoft/Boot/hr-HR:
total 164
drwxr-xr-x  2 root root  4096 Oct 23 13:26 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 76640 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 76640 Oct 23 15:52 bootmgr.efi.mui

/boot/efi/EFI/Microsoft/Boot/hu-HU:
total 220
drwxr-xr-x  2 root root  4096 Mar 29  2016 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 78688 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 78688 Oct 23 15:52 bootmgr.efi.mui
-rwxr-xr-x  1 root root 45920 Oct 23 15:52 memtest.efi.mui

/boot/efi/EFI/Microsoft/Boot/it-IT:
total 212
drwxr-xr-x  2 root root  4096 Mar 29  2016 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 77152 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 77152 Oct 23 15:52 bootmgr.efi.mui
-rwxr-xr-x  1 root root 45408 Oct 23 15:52 memtest.efi.mui

/boot/efi/EFI/Microsoft/Boot/ja-JP:
total 192
drwxr-xr-x  2 root root  4096 Mar 29  2016 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 67424 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 67424 Oct 23 15:52 bootmgr.efi.mui
-rwxr-xr-x  1 root root 42848 Oct 23 15:52 memtest.efi.mui

/boot/efi/EFI/Microsoft/Boot/ko-KR:
total 192
drwxr-xr-x  2 root root  4096 Mar 29  2016 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 66912 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 66912 Oct 23 15:52 bootmgr.efi.mui
-rwxr-xr-x  1 root root 42848 Oct 23 15:52 memtest.efi.mui

/boot/efi/EFI/Microsoft/Boot/lt-LT:
total 164
drwxr-xr-x  2 root root  4096 Oct 23 13:26 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 75616 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 75616 Oct 23 15:52 bootmgr.efi.mui

/boot/efi/EFI/Microsoft/Boot/lv-LV:
total 164
drwxr-xr-x  2 root root  4096 Oct 23 13:26 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 75616 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 75616 Oct 23 15:52 bootmgr.efi.mui

/boot/efi/EFI/Microsoft/Boot/nb-NO:
total 212
drwxr-xr-x  2 root root  4096 Mar 29  2016 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 75616 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 75616 Oct 23 15:52 bootmgr.efi.mui
-rwxr-xr-x  1 root root 45408 Oct 23 15:52 memtest.efi.mui

/boot/efi/EFI/Microsoft/Boot/nl-NL:
total 220
drwxr-xr-x  2 root root  4096 Mar 29  2016 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 78176 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 78176 Oct 23 15:52 bootmgr.efi.mui
-rwxr-xr-x  1 root root 45408 Oct 23 15:52 memtest.efi.mui

/boot/efi/EFI/Microsoft/Boot/pl-PL:
total 212
drwxr-xr-x  2 root root  4096 Mar 29  2016 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 77664 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 77664 Oct 23 15:52 bootmgr.efi.mui
-rwxr-xr-x  1 root root 45920 Oct 23 15:52 memtest.efi.mui

/boot/efi/EFI/Microsoft/Boot/pt-BR:
total 212
drwxr-xr-x  2 root root  4096 Mar 29  2016 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 76640 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 76640 Oct 23 15:52 bootmgr.efi.mui
-rwxr-xr-x  1 root root 45408 Oct 23 15:52 memtest.efi.mui

/boot/efi/EFI/Microsoft/Boot/pt-PT:
total 212
drwxr-xr-x  2 root root  4096 Mar 29  2016 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 76640 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 76640 Oct 23 15:52 bootmgr.efi.mui
-rwxr-xr-x  1 root root 45920 Oct 23 15:52 memtest.efi.mui

/boot/efi/EFI/Microsoft/Boot/qps-ploc:
total 68
drwxr-xr-x  2 root root  4096 Mar 29  2016 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 54112 Mar  4 08:13 memtest.efi.mui

/boot/efi/EFI/Microsoft/Boot/Resources:
total 44
drwxr-xr-x  3 root root  4096 Mar 29  2016 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 26976 Jul 16  2016 bootres.dll
drwxr-xr-x  2 root root  4096 Mar 29  2016 en-US

/boot/efi/EFI/Microsoft/Boot/Resources/en-US:
total 12
drwxr-xr-x 2 root root 4096 Mar 29  2016 .
drwxr-xr-x 3 root root 4096 Mar 29  2016 ..
-rwxr-xr-x 1 root root 3584 Jul 16  2016 bootres.dll.mui

/boot/efi/EFI/Microsoft/Boot/ro-RO:
total 164
drwxr-xr-x  2 root root  4096 Oct 23 13:26 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 76128 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 76128 Oct 23 15:52 bootmgr.efi.mui

/boot/efi/EFI/Microsoft/Boot/ru-RU:
total 208
drwxr-xr-x  2 root root  4096 Mar 29  2016 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 77152 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 77152 Oct 23 15:52 bootmgr.efi.mui
-rwxr-xr-x  1 root root 44896 Oct 23 15:52 memtest.efi.mui

/boot/efi/EFI/Microsoft/Boot/sk-SK:
total 164
drwxr-xr-x  2 root root  4096 Oct 23 13:26 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 77152 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 77152 Oct 23 15:52 bootmgr.efi.mui

/boot/efi/EFI/Microsoft/Boot/sl-SI:
total 164
drwxr-xr-x  2 root root  4096 Oct 23 13:26 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 76640 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 76640 Oct 23 15:52 bootmgr.efi.mui

/boot/efi/EFI/Microsoft/Boot/sr-Latn-CS:
total 60
drwxr-xr-x  2 root root  4096 Mar 29  2016 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 45408 Mar  4 08:13 memtest.efi.mui

/boot/efi/EFI/Microsoft/Boot/sr-Latn-RS:
total 164
drwxr-xr-x  2 root root  4096 Oct 23 13:26 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 77152 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 77152 Oct 23 15:52 bootmgr.efi.mui

/boot/efi/EFI/Microsoft/Boot/sv-SE:
total 208
drwxr-xr-x  2 root root  4096 Mar 29  2016 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 76128 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 76128 Oct 23 15:52 bootmgr.efi.mui
-rwxr-xr-x  1 root root 44896 Oct 23 15:52 memtest.efi.mui

/boot/efi/EFI/Microsoft/Boot/tr-TR:
total 212
drwxr-xr-x  2 root root  4096 Mar 29  2016 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 75104 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 75104 Oct 23 15:52 bootmgr.efi.mui
-rwxr-xr-x  1 root root 45408 Oct 23 15:52 memtest.efi.mui

/boot/efi/EFI/Microsoft/Boot/uk-UA:
total 164
drwxr-xr-x  2 root root  4096 Oct 23 13:26 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 77152 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 77152 Oct 23 15:52 bootmgr.efi.mui

/boot/efi/EFI/Microsoft/Boot/zh-CN:
total 184
drwxr-xr-x  2 root root  4096 Mar 29  2016 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 63840 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 63840 Oct 23 15:52 bootmgr.efi.mui
-rwxr-xr-x  1 root root 42336 Oct 23 15:52 memtest.efi.mui

/boot/efi/EFI/Microsoft/Boot/zh-HK:
total 184
drwxr-xr-x  2 root root  4096 Mar 29  2016 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 63840 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 63840 Oct 23 15:52 bootmgr.efi.mui
-rwxr-xr-x  1 root root 42336 Oct 23 15:52 memtest.efi.mui

/boot/efi/EFI/Microsoft/Boot/zh-TW:
total 184
drwxr-xr-x  2 root root  4096 Mar 29  2016 .
drwxr-xr-x 42 root root  8192 Mar 29  2016 ..
-rwxr-xr-x  1 root root 63840 Oct 23 15:52 bootmgfw.efi.mui
-rwxr-xr-x  1 root root 63840 Oct 23 15:52 bootmgr.efi.mui
-rwxr-xr-x  1 root root 42336 Oct 23 15:52 memtest.efi.mui

/boot/efi/EFI/Microsoft/Recovery:
total 52
drwxr-xr-x 2 root root  4096 Mar 29  2016 .
drwxr-xr-x 4 root root  4096 Mar 29  2016 ..
-rwxr-xr-x 1 root root 20480 Oct 23 13:55 BCD
-rwxr-xr-x 1 root root 24576 Mar 29  2016 BCD.LOG
-rwxr-xr-x 1 root root     0 Mar 29  2016 BCD.LOG1
-rwxr-xr-x 1 root root     0 Mar 29  2016 BCD.LOG2

/boot/efi/loader:
total 16
drwxr-xr-x 3 root root 4096 Apr  4 07:59 .
drwxr-xr-x 6 root root 4096 Dec 31  1969 ..
drwxr-xr-x 2 root root 4096 Apr  3 11:11 entries
-rwxr-xr-x 1 root root   38 Apr  4 07:59 loader.conf

/boot/efi/loader/entries:
total 16
drwxr-xr-x 2 root root 4096 Apr  3 11:11 .
drwxr-xr-x 3 root root 4096 Apr  4 07:59 ..
-rwxr-xr-x 1 root root  238 Mar 27 10:35 Solus-lts-4.9.18-10.conf
-rwxr-xr-x 1 root root  238 Apr  2 09:27 Solus-lts-4.9.20-12.conf

'/boot/efi/System Volume Information':
total 12
drwxr-xr-x 2 root root 4096 Oct 23 13:26 .
drwxr-xr-x 6 root root 4096 Dec 31  1969 ..
-rwxr-xr-x 1 root root   76 Oct 23 13:26 IndexerVolumeGuid

/boot/efi/.Trash-1000:
total 16
drwxr-xr-x 4 root root 4096 Oct 14 01:22 .
drwxr-xr-x 6 root root 4096 Dec 31  1969 ..
drwxr-xr-x 2 root root 4096 Oct 14 01:22 files
drwxr-xr-x 2 root root 4096 Oct 14 01:22 info

/boot/efi/.Trash-1000/files:
total 1140
drwxr-xr-x 2 root root    4096 Oct 14 01:22 .
drwxr-xr-x 4 root root    4096 Oct 14 01:22 ..
-rwxr-xr-x 1 root root 1159008 Oct 29  2015 bootx64.efi

/boot/efi/.Trash-1000/info:
total 12
drwxr-xr-x 2 root root 4096 Oct 14 01:22 .
drwxr-xr-x 4 root root 4096 Oct 14 01:22 ..
-rwxr-xr-x 1 root root   72 Oct 14 01:22 bootx64.efi.trashinfo




$ ls -lRa /usr/lib/kernel
/usr/lib/kernel:
total 30312
drwxr-xr-x   3 root root     4096 Apr  3 11:13 .
drwxr-xr-x 156 root root    69632 Apr  4 11:00 ..
-rw-r--r--   1 root root       15 Mar 31 13:58 cmdline-4.9.20-12.lts
-rwxr-xr-x   1 root root  6903376 Mar 31 13:58 com.solus-project.lts.4.9.20-12
-rw-r--r--   1 root root   177768 Mar 31 13:58 config-4.9.20-12.lts
lrwxrwxrwx   1 root root       31 Apr  3 11:13 default-lts -> com.solus-project.lts.4.9.20-12
-rw-------   1 root root 20343328 Mar 31 13:58 initrd-com.solus-project.lts.4.9.20-12
drwxr-xr-x   2 root root     4096 Apr  3 11:14 install.d
-rw-r--r--   1 root root  3522632 Mar 31 13:58 System.map-4.9.20-12.lts

/usr/lib/kernel/install.d:
total 24
drwxr-xr-x 2 root root 4096 Apr  3 11:14 .
drwxr-xr-x 3 root root 4096 Apr  3 11:13 ..
-rwxr-xr-x 1 root root  191 Mar 28 20:05 50-depmod.install
-rwxr-xr-x 1 root root 1242 Mar 31 16:32 50-dracut.install
-rwxr-xr-x 1 root root 2263 Mar 31 16:32 51-dracut-rescue.install
-rwxr-xr-x 1 root root 2040 Mar 28 20:05 90-loaderentry.install

**Comment by ikeydoherty** [comment]
OK so in a fully booted system, when running the `4.9.20`, just run:

`sudo clr-boot-manager update`

Note that you're always going to have multiple kernel versions going forward, thats how CBM works. The idea is that when you get the *next* update, the previous to current is removed.

**Comment by tayspen72** [comment]
OK. I have ran that command but you're saying I can just count on the next kernel update to remove the previous kernels. Thanks for the quick response. Very much appreciated

**Comment by ikeydoherty** [comment]
np. What we do for UEFI is actually set the default kernel entry. So if you're using `linux-lts`, when you reboot it'll automatically select the new kernel each time, meaning you don't need to do anything yourself :)
